services:
  app:
    container_name: Dash_app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports: 
      - 7051:7050

  mkdocs:
    image: squidfunk/mkdocs-material
    container_name: idh-docs
    restart: always
    ports:
      - "8005:8000"
    volumes:
      - ./:/docs
    stdin_open: true
    tty: true
