services:
  database:
    image: postgres:17
    container_name: api_database
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    volumes:
      - database_volume:/var/lib/postgresql/data

volumes:
  database_volume:
