name: research_env
channels:
  - conda-forge
dependencies:
  - pip=23.3.1
  - python=3.12
  - numpy=1.26.4
  - pandas=2.1.4
  - scipy=1.11.4
  - pyarrow=14.0.2
  - polars=0.20.21
  - ipykernel=6.23.0
  - pip:
      - world_bank_data==0.1.3