"""added hincp column

Revision ID: 7460a4ebe363
Revises: 83f2e27a02ee
Create Date: 2025-01-12 14:14:10.802279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7460a4ebe363'
down_revision: Union[str, None] = '83f2e27a02ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pumspr', sa.Column('hincp', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pumspr', 'hincp')
    # ### end Alembic commands ###
