"""initial migrations

Revision ID: 83f2e27a02ee
Revises: 
Create Date: 2025-01-12 14:01:58.768005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '83f2e27a02ee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pumspr',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('agep', sa.Integer(), nullable=False),
    sa.Column('sch', sa.Integer(), nullable=False),
    sa.Column('schl', sa.Integer(), nullable=False),
    sa.Column('pwgtp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pumspr')
    # ### end Alembic commands ###
