"""initial migrations

Revision ID: 8ad69fa61d1f
Revises: 
Create Date: 2025-01-14 10:46:14.156953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8ad69fa61d1f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gnitable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('constant', sa.Float(), nullable=False),
    sa.Column('capita', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pumstable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('agep', sa.Integer(), nullable=False),
    sa.Column('sch', sa.Integer(), nullable=False),
    sa.Column('schl', sa.Integer(), nullable=False),
    sa.Column('hincp', sa.Integer(), nullable=False),
    sa.Column('pwgtp', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pumstable')
    op.drop_table('gnitable')
    # ### end Alembic commands ###
